# Generated by Django 4.0.5 on 2022-06-18 11:49

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='UID', primary_key=True, serialize=False, verbose_name='UID')),
                ('name', models.CharField(help_text='Name', max_length=250, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='UID', primary_key=True, serialize=False, verbose_name='UID')),
                ('name', models.CharField(help_text='Name', max_length=250, unique=True, verbose_name='Name')),
                ('text', models.TextField(blank=True, help_text='Text', null=True, verbose_name='Text')),
                ('image', models.ImageField(blank=True, help_text='Image', null=True, upload_to='', verbose_name='Image')),
                ('tags', models.ManyToManyField(to='post.tag', verbose_name='tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
