# Generated by Django 4.0.5 on 2022-06-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=None, help_text='Text', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
