# Generated by Django 4.0.5 on 2022-07-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options_remove_tag_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='post.tag', verbose_name='posts'),
        ),
    ]
