# Generated by Django 4.0.5 on 2022-06-18 20:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='UID', primary_key=True, serialize=False, verbose_name='UID')),
                ('name', models.CharField(help_text='Name', max_length=250, unique=True, verbose_name='Name')),
                ('score', models.PositiveIntegerField(default=0, help_text='Score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score')),
                ('blockchain', models.CharField(choices=[('BSC', 'BSC'), ('Etherium', 'Etherium')], help_text='Blockchain', max_length=20, verbose_name='Blockchain')),
                ('category', models.CharField(help_text='Category', max_length=250, verbose_name='Category')),
                ('image', models.ImageField(help_text='Image', upload_to='', verbose_name='Image')),
                ('audit', models.URLField(help_text='Audit', max_length=1000, verbose_name='Audit')),
                ('audit_date', models.DateTimeField(help_text='Audit date', verbose_name='Audit date')),
                ('is_partner', models.BooleanField(default=False, help_text='Is partner', verbose_name='Is partner')),
                ('contract_address', models.CharField(help_text='Contract address', max_length=250, verbose_name='Contract address')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
