# Generated by Django 4.0.5 on 2022-07-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Number', null=True, verbose_name='Number'),
        ),
    ]
