# Generated by Django 4.0.5 on 2022-07-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter', max_length=1000, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='token',
            name='website',
            field=models.URLField(blank=True, help_text='Website', max_length=1000, null=True, verbose_name='Website'),
        ),
    ]
