# Generated by Django 4.0.5 on 2022-07-06 10:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_token_twitter_token_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='UID', primary_key=True, serialize=False, verbose_name='UID')),
                ('name', models.CharField(help_text='Name', max_length=250, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='token',
            name='number',
        ),
        migrations.AddField(
            model_name='token',
            name='blockchain_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.blockchain', verbose_name='tokens'),
        ),
    ]
