# Generated by Django 4.0.5 on 2022-07-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_blockchain_remove_token_number_token_blockchain_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='blockchain_new',
            field=models.ForeignKey(blank=True, help_text='Blockchain', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.blockchain', verbose_name='Blockchain'),
        ),
    ]
