# Generated by Django 4.0.5 on 2022-07-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_token_blockchain_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='blockchain',
        ),
    ]
