# Generated by Django 4.0.5 on 2022-07-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_token_blockchain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='blockchain_new',
            new_name='blockchain',
        ),
    ]
