# Generated by Django 4.0.5 on 2022-07-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_blockchain_new_token_blockchain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('-audit_date',)},
        ),
        migrations.AlterField(
            model_name='token',
            name='contract_address',
            field=models.CharField(blank=True, help_text='Contract address', max_length=250, null=True, verbose_name='Contract address'),
        ),
    ]
