# Generated by Django 4.0.5 on 2022-07-09 15:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_token_options_alter_token_contract_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Image', keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to='', verbose_name='Image'),
        ),
    ]
