# Generated by Django 4.0.5 on 2022-07-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_token_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='telegram',
            field=models.URLField(blank=True, help_text='Telegram', max_length=1000, null=True, verbose_name='Telegram'),
        ),
    ]
