# Generated by Django 4.0.5 on 2022-08-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_token_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='blockchain',
            field=models.ForeignKey(help_text='Blockchain', on_delete=django.db.models.deletion.CASCADE, to='project.blockchain', verbose_name='Blockchain'),
        ),
        migrations.AlterField(
            model_name='token',
            name='contract_address',
            field=models.CharField(help_text='Contract address', max_length=250, verbose_name='Contract address'),
        ),
    ]
