# Generated by Django 4.0.5 on 2022-09-17 13:13

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_token_blockchain_alter_token_contract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Image', keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='link',
            field=models.URLField(blank=True, help_text='Link', max_length=1000, null=True, verbose_name='Link'),
        ),
    ]
