# Generated by Django 4.0.5 on 2022-09-17 14:13

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_token_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='categories',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, help_text='Categories', null=True, size=None, verbose_name='Categories'),
        ),
    ]
