# Generated by Django 4.0.5 on 2022-09-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_token_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='category',
        ),
    ]
