# Generated by Django 4.0.5 on 2022-09-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_remove_token_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='index',
            field=models.PositiveIntegerField(default=0, help_text='Index', verbose_name='Index'),
        ),
    ]
